### ISSUE TITLE
gitlab url/token

### ISSUE THREAD

**Issue by kurt-o-sys** [novotnyr/gitlab-quickmr-idea-plugin#1]
I'm trying to setup this plugin, but I seem to fail:
1. Get a personal access token from gitlab (User Settings - Access Tokens)
2. In the plugin settings in intellij:
  * Gitlab URL: the base url https://hosted-gitlab.domain.com .
  * Access Token: Personal Access Token from step 1

If I try to validate: 
_Server is not available. Please check URL or access token_

I've tried other URL's as well (`/api` or `/api/v4`).

What am I missing?

**Comment by novotnyr** [comment]
Until we improve the connection debugging, please make sure that a basic `curl` check is operational:

    curl -H "Private-Token: dxfnsif"  https://gitlab.domain.com/api/v4/version

The similar check is used to verify host within the plugin.

**Comment by bluefish6** [comment]
I have the same issue as well.

results:
```
curl -H "Private-Token: someredactedtoken"  https://gitlab.somedomain.com/api/v4/version
{"version":"11.2.3-ee","revision":"aadca99"}
```

![image](https://user-images.githubusercontent.com/3324881/48919544-a9bae080-ee93-11e8-8b9a-a946d6c20063.png)

Any idea how can I help with debugging this?

**Comment by novotnyr** [comment]
@bluefish6 I have improved on the error messages in ba3496ece487eaa98da8032b6c2a16ada8071aee Please download and install a build version below and try again. 

Also, remember that credentials/API tokens are now stored in IntelliJ native keychain instead of plaintext project settings. You might need to reapply token settings in the Preferences to store it properly.


[gitlab-quickmr-idea-plugin.zip](https://github.com/novotnyr/gitlab-quickmr-idea-plugin/files/2610001/gitlab-quickmr-idea-plugin.zip)

**Comment by bluefish6** [comment]
thanks. It showed me a 404 response and after snooping around, I found the cause of problem:

I was providing the "base url" as `https://gitlab.domain.com` and should have used `https://gitlab.domain.com/api/v4` instead. Maybe a good idea would be to require only the base gitlab url and append `/api/v4` in the plugin, as this url would be the same regardless of API version (and plugin) updates in the future.

**Comment by novotnyr** [comment]
@bluefish6 Base URL can be quite tricky and with the current design it might require much more engineering effort (let's call it poor design). However, based on your suggestion I have improved the validation message even more to explicitly point to the URL format.

**Comment by novotnyr** [comment]
Closing as the improved validation has been put in place.

**Comment by lacoprof** [comment]
I have same problem, it is possible to connect to gitlab with curl -k insecure option ? Our gitlab installation 
When i use 
curl -H "Private-Token: my_token"  https://our_gitlab_installation_host/api/v4/version
 i get 
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
when i add -k option
curl -H -k "Private-Token: my_token"  https://our_gitlab_installation_host/api/v4/version
i get correct response {"version":"10.8.4","revision":"2268d0c"}

**Comment by novotnyr** [comment]
@lacoprof Thank you. Moving this to a separate issue #9.

**Comment by AndroidDeveloperLB** [comment]
I'm also stuck on this step: 

"Then, specify GitLab URL and REST Access Token and enter default target branch for Merge Request and a title."

Given that I'm logged in to the Gitlab website, how do I get the URL that has "/api" in it, and then a token for it?

**Comment by novotnyr** [comment]
I have updated the docs. 

* GitLab.com: 
    * GitLab URL: https://gitlab.com/api/v4
    * Personal Access Token: https://gitlab.com/profile/personal_access_tokens
* Private instance hosted at gitlab.example.com:
    * GitLab URL: https://gitlab.example.com/api/v4
    * Personal Access Token: https://gitlab.example.com/profile/personal_access_tokens

**Comment by AndroidDeveloperLB** [comment]
@novotnyr I still don't get it right.
I've changed the URL to end with "/api/v4" , and the plugin still says it's not ok:

![image](https://user-images.githubusercontent.com/5357526/69133096-014b5680-0abe-11ea-8aba-8e28b87bf899.png)

And what do I do on the "https://git..../profile/personal_access_tokens" ? 
I already have an access token, but I can't find how to get its info:

![image](https://user-images.githubusercontent.com/5357526/69133312-5c7d4900-0abe-11ea-910c-dad8d4e0ca05.png)

**Comment by novotnyr** [comment]
You cannot get info about existing token. This is due to security reasons.

However, you can create as many Personal Access Tokens as you want. 

On my machine, I have created a new Personal Access Token (*api* scope). I copied the token to the clipboard and used that in the plugin.

**Comment by AndroidDeveloperLB** [comment]
@novotnyr Suppose I create a new one, what should I do about the URL?
It says it's invalid.
Also, after I have those two, is it enough, or should I do more?

**Comment by novotnyr** [comment]
Your URL looks good to me. I think your issues will resolve automatically with your new valid token. Please note that the error message says _Unauthorized_, which happens with missing, expired or illegal Personal Access Tokens.

**Comment by AndroidDeveloperLB** [comment]
@novotnyr Still having issues. I had to set default target branch and title, so I have.
However, when it's time to add assignee, it doesn't let me. Pressing the "+" button doesn't do anything.

![image](https://user-images.githubusercontent.com/5357526/69609501-58a77480-1032-11ea-9f0c-70ae02f39bf9.png)

[2019-11-26_09-51-01.zip](https://github.com/novotnyr/gitlab-quickmr-idea-plugin/files/3890617/2019-11-26_09-51-01.zip)

**Comment by novotnyr** [comment]
@AndroidDeveloperLB The URL is not valid. Are you sure that there is no whitespace after `/v4`?

**Comment by AndroidDeveloperLB** [comment]
@novotnyr Yes, there is no space there.
Also, as I said, there is no way to add assignee. Maybe because it fails to get there.

**Comment by novotnyr** [comment]
Unfortunately, you cannot add assignees if the validation URL fails. Are you positively sure your URL validated via _Test Connection_ button? (According to screenshot it did not. Still, that failure puzzles me.)

**Comment by AndroidDeveloperLB** [comment]
@novotnyr The tooltip error showed it failed.

**Comment by novotnyr** [comment]
This might be connected to #15. Please watch that issue for further bugfixes.

**Comment by novotnyr** [comment]
@AndroidDeveloperLB  also, please try this v13 prerelease to see if the exception message helps you.

[gitlab-quickmr-idea-plugin.zip](https://github.com/novotnyr/gitlab-quickmr-idea-plugin/files/3913391/gitlab-quickmr-idea-plugin.zip)

**Comment by AndroidDeveloperLB** [comment]
@novotnyr How do I install this?

**Comment by novotnyr** [comment]
Please have a look on this: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by AndroidDeveloperLB** [comment]
Got a weird issue because of this: Now I can't press on "Tools" menu item. It's disabled:

![image](https://user-images.githubusercontent.com/5357526/70601644-2e8daf00-1bfb-11ea-9255-02473917bd36.png)

Also, still got this:

![image](https://user-images.githubusercontent.com/5357526/70601678-4b29e700-1bfb-11ea-9952-8958b0c6b87d.png)

**Comment by novotnyr** [comment]
Your GitLab API URL is not valid. As the warning says, it should not return a 404 and a HTML.

I think you should contact your GitLab instance administrators for help.

**Comment by AndroidDeveloperLB** [comment]
@novotnyr OK I talked to him. I see what the problem was. The URL included too many parts, of the project instead of the base URL. I will be able to see if it works when I use it for real, but at least now it says it's valid.

That being said, the issue of "Tools" menu item being disabled still exists.

**Comment by novotnyr** [comment]
I cannot comment on the Tools menu item being disabled. This should not be affected by this plugin.
This plugin contributes to the Git context menu which is under different top-level menu (VCS).
